repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
#    -   id: flake8
#        name: flake8
#        entry: nox -rs lint
#        language: system
#        types: [python]
