version: "3.1"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    # env_file:
    #     - ./.env
    expose:
      - "5432"
    environment:
      DB_HOST: db
      DB_NAME: so
      DB_USER: root
      DB_PASS: secretpassword
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  mysqldata:
