version: "3.1"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    # env_file:
    #     - ./.env
    expose:
      - "5432"
    environment:
      DB_HOST: db
      DB_NAME: so
      DB_USER: postgres
      DB_PASS: secretpassword
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: secretpassword

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    ports:
      - 5050:80

volumes:
  pgdata:
