# Generated by Django 3.1.7 on 2021-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210228_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='boec',
            field=models.ManyToManyField(blank=True, related_name='brigades', to='core.Boec'),
        ),
    ]
