# Generated by Django 3.1.12 on 2021-06-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210611_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worth', models.IntegerField(choices=[(0, 'Волонтер'), (1, 'Организатор')], verbose_name='Статус участия')),
                ('boec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participation', to='core.boec', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'verbose_name_plural': 'Участники мероприятия',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='EventOrder',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant', to='core.event', verbose_name='Мероприятие'),
        ),
    ]
