# Generated by Django 3.1.12 on 2021-06-15 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_auto_20210612_1221")]

    operations = [
        migrations.RemoveField(model_name="event", name="organizer"),
        migrations.RemoveField(model_name="event", name="volonteer"),
        migrations.AlterField(
            model_name="event",
            name="worth",
            field=models.IntegerField(
                choices=[
                    (0, "Не учитывается"),
                    (1, "Творчество"),
                    (2, "Спорт"),
                    (3, "Волонтерство"),
                    (4, "Городское"),
                ],
                default=0,
                verbose_name="Ценность блоков",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="worth",
            field=models.IntegerField(
                choices=[(0, "Волонтер"), (1, "Организатор"), (2, "Участник")],
                default=2,
                verbose_name="Статус участия",
            ),
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="core.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={"verbose_name": "Номинация", "verbose_name_plural": "Номинации"},
        ),
        migrations.CreateModel(
            name="BrigadeParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sportPlace",
                    models.IntegerField(
                        choices=[(1, "Первое"), (2, "Второе"), (3, "Третье")],
                        null=True,
                        verbose_name="Спортивное место",
                    ),
                ),
                (
                    "boecs",
                    models.ManyToManyField(
                        blank=True, related_name="brigadeParticipant", to="core.Boec"
                    ),
                ),
                (
                    "brigades",
                    models.ManyToManyField(
                        blank=True, related_name="brigadeParticipant", to="core.Brigade"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="brigadeParticipant",
                        to="core.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "nomination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="brigadeParticipant",
                        to="core.nomination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка отряда на мероприятия",
                "verbose_name_plural": "Заявки отрядов на мероприятия",
            },
        ),
    ]
