# Generated by Django 3.1.7 on 2021-03-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210306_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.brigade')),
                ('participations', models.ManyToManyField(blank=True, related_name='event_participations', to='core.Boec')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проведение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, related_name='organizers_list', to='core.Boec', verbose_name='Организаторы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='shtab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shtab', verbose_name='Штаб'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='event',
            name='volonteer',
            field=models.ManyToManyField(blank=True, related_name='volonteers_list', to='core.Boec', verbose_name='Волонтеры'),
        ),
        migrations.CreateModel(
            name='EventWin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'Первое место'), (2, 'Второе место'), (3, 'Третье место')], verbose_name='Ценность блоков')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='core.eventorder', verbose_name='Заявка')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='event_orders', to='core.EventOrder', verbose_name='Заявки на участие (или участие в соревнованиях)'),
        ),
        migrations.AddField(
            model_name='event',
            name='participations',
            field=models.ManyToManyField(blank=True, related_name='event_participations', to='core.EventOrder', verbose_name='Участие в конкурсной программе (или плей-офф)'),
        ),
        migrations.AddField(
            model_name='event',
            name='win',
            field=models.ManyToManyField(blank=True, related_name='event_win', to='core.EventWin', verbose_name='Победы'),
        ),
    ]
