# Generated by Django 3.1.7 on 2021-03-06 11:17

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210306_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participations',
        ),
        migrations.RemoveField(
            model_name='event',
            name='win',
        ),
        migrations.AddField(
            model_name='eventorder',
            name='event',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='core.event', verbose_name='Мероприятие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventorder',
            name='isСontender',
            field=models.BooleanField(default=False, verbose_name=core.models.Event),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='place',
            field=models.IntegerField(blank=True, choices=[(1, 'Первое место'), (2, 'Второе место'), (3, 'Третье место')], null=True),
        ),
        migrations.DeleteModel(
            name='EventWin',
        ),
    ]
