# Generated by Django 3.1.12 on 2021-06-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210615_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brigadeparticipant",
            name="nomination",
        ),
        migrations.AddField(
            model_name="brigadeparticipant",
            name="nominations",
            field=models.ManyToManyField(
                blank=True, related_name="brigadeParticipant", to="core.Nomination"
            ),
        ),
    ]
