# Generated by Django 3.1.7 on 2021-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210306_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorder',
            name='isСontender',
            field=models.BooleanField(default=False),
        ),
    ]
