# Generated by Django 3.1.12 on 2021-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20210615_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
