# Generated by Django 3.1.5 on 2021-01-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('DOB', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('boec', models.ManyToManyField(to='core.Boec')),
                ('shtab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shtab')),
            ],
        ),
    ]
