# Generated by Django 3.1.7 on 2021-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210307_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='worth',
            field=models.IntegerField(choices=[('0', 'Не учитывается'), ('1', 'Творчество'), ('2', 'Спорт'), ('3', 'Волонтерство'), ('4', 'Городское')], default='0', verbose_name='Ценность блоков'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='place',
            field=models.CharField(blank=True, choices=[('1', 'Первое место'), ('2', 'Второе место'), ('3', 'Третье место')], max_length=5, null=True, verbose_name='Занятое место'),
        ),
    ]
