# Generated by Django 3.1.12 on 2021-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0010_auto_20210616_1223")]

    operations = [
        migrations.RemoveField(model_name="competitionparticipant", name="brigade"),
        migrations.AddField(
            model_name="competitionparticipant",
            name="brigades",
            field=models.ManyToManyField(
                blank=True, related_name="competition_participation", to="core.Brigade"
            ),
        ),
    ]
