# Generated by Django 3.1.5 on 2021-01-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210107_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.area'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='shtab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.shtab'),
        ),
    ]
