# Generated by Django 3.1.7 on 2021-03-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210309_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventorder',
            old_name='brigade',
            new_name='brigades',
        ),
    ]
