# Generated by Django 3.1.5 on 2021-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210107_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='boec',
            field=models.ManyToManyField(blank=True, to='core.Boec'),
        ),
    ]
