# Generated by Django 3.1.5 on 2021-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210107_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
