# Generated by Django 3.1.7 on 2021-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_event_iscanonical"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="isTicketed",
            field=models.BooleanField(default=False, verbose_name="Вход по билетам"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место проведения"
            ),
        ),
    ]
