# Generated by Django 3.1.12 on 2021-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20210629_2000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionparticipant",
            name="boec",
            field=models.ManyToManyField(
                blank=True, related_name="competition_participation", to="core.Boec"
            ),
        ),
    ]
