# Generated by Django 3.1.5 on 2021-01-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210107_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Just Created'), (1, 'Passen'), (2, 'Not Passed')], default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('visibility', models.BooleanField(default=False)),
                ('organizer', models.ManyToManyField(blank=True, related_name='organizers_list', to='core.Boec')),
                ('shtab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shtab')),
                ('volonteer', models.ManyToManyField(blank=True, related_name='volonteers_list', to='core.Boec')),
            ],
        ),
    ]
