# Generated by Django 3.1.7 on 2021-07-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_ticket_ticketscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="uuid",
            field=models.UUIDField(default=None, null=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="ticketscan",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_scans",
                to="core.ticket",
                verbose_name="Билет",
            ),
        ),
    ]
