# Generated by Django 3.1.5 on 2021-01-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210107_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
