# Generated by Django 3.1.5 on 2021-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210107_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Just Created'), (1, 'Passed'), (2, 'Not Passed')], default=0),
        ),
    ]
