# Generated by Django 3.1.12 on 2021-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20210702_1732"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitionparticipant",
            name="isRated",
        ),
        migrations.AddField(
            model_name="competition",
            name="ratingless",
            field=models.BooleanField(default=False),
        ),
    ]
