# Generated by Django 3.1.12 on 2021-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20210702_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="isAccepted",
            field=models.BooleanField(default=False, verbose_name="Подтвержден"),
        ),
        migrations.AddField(
            model_name="season",
            name="isCandidate",
            field=models.BooleanField(default=True, verbose_name="Не стал бойцом"),
        ),
    ]
