# Generated by Django 3.1.5 on 2021-01-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210107_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boec',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='DOB',
        ),
    ]
