# Generated by Django 3.1.5 on 2021-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210116_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='boec',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='brigade',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
