# Generated by Django 3.1.13 on 2021-07-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20210703_1833"),
        ("core", "0020_auto_20210710_1822"),
    ]

    operations = []
