# Generated by Django 3.1.13 on 2021-07-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_merge_20210711_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tickets",
                to="core.event",
                verbose_name="Мероприятие",
            ),
        ),
    ]
