# Generated by Django 3.1.5 on 2021-01-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210116_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boec',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
