# Generated by Django 3.1.13 on 2021-07-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20210711_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="brigade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.brigade",
                verbose_name="Отряд",
            ),
        ),
    ]
