# Generated by Django 3.1.5 on 2021-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210116_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
