# Generated by Django 3.1.13 on 2021-07-16 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_participant_isapproved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Предупреждение",
                "verbose_name_plural": "Предупреждения",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Информация"),
                            (1, "Предупреждение"),
                            (2, "Достижение"),
                        ],
                        default=0,
                        verbose_name="Тип",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("seen", models.BooleanField(default=False)),
                (
                    "boec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="activities",
                        to="core.boec",
                        verbose_name="Боец",
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="activities",
                        to="core.warning",
                        verbose_name="Предупреждение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Конференции",
            },
        ),
    ]
