# Generated by Django 3.1.13 on 2021-07-16 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_boec_unreadactivitycount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            ("paticipation_count", "Посещение мероприятия"),
                            ("volonteer_count", "Волонтерство"),
                            ("organizer_count", "Организаторство"),
                            ("competition_default", "Подача заявки"),
                            ("competition_playoff", "Прохождение в плейофф"),
                            ("nominations", "Номинации"),
                            ("seasons", "Сезоны"),
                            ("sport_wins", "Номинация в спорте"),
                            ("art_wins", "Номинация в творчестве"),
                        ],
                        verbose_name="Тип",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("title", models.TextField(max_length=255)),
                ("goal", models.IntegerField(verbose_name="Цель")),
                (
                    "boec",
                    models.ManyToManyField(
                        blank=True, related_name="achievements", to="core.Boec"
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
    ]
