# Generated by Django 3.1.13 on 2021-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_achievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="type",
            field=models.TextField(
                choices=[
                    ("paticipation_count", "Посещение мероприятия"),
                    ("volonteer_count", "Волонтерство"),
                    ("organizer_count", "Организаторство"),
                    ("competition_default", "Подача заявки"),
                    ("competition_playoff", "Прохождение в плейофф"),
                    ("nominations", "Номинации"),
                    ("seasons", "Сезоны"),
                    ("sport_wins", "Номинация в спорте"),
                    ("art_wins", "Номинация в творчестве"),
                ],
                verbose_name="Тип",
            ),
        ),
    ]
