# Generated by Django 3.1.13 on 2021-07-16 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20210716_1920"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="achievement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="activities",
                to="core.achievement",
                verbose_name="Достижение",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="warning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="activities",
                to="core.warning",
                verbose_name="Предупреждение",
            ),
        ),
    ]
